# Generated by Django 5.0.4 on 2024-08-06 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentid', models.AutoField(primary_key=True, serialize=False)),
                ('departmentname', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('electionType', models.CharField(choices=[('Candidates', 'Candidates'), ('Topics', 'Topics')], default='Candidates', max_length=10)),
                ('candidates', models.JSONField(blank=True, null=True)),
                ('topics', models.JSONField(blank=True, null=True)),
                ('voters', models.JSONField(blank=True, null=True)),
                ('votersDept', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Ongoing', 'Ongoing')], default='Scheduled', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'elections',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('usertypeid', models.AutoField(primary_key=True, serialize=False)),
                ('usertype', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'user_types',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('usertype', models.CharField(default='Voter', max_length=255)),
                ('department', models.ForeignKey(blank=True, db_column='department', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.department', to_field='departmentname')),
            ],
            options={
                'db_table': 'user_accounts',
            },
        ),
        migrations.CreateModel(
            name='ElectionVoterStatus',
            fields=[
                ('election_voter_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('has_voted', models.BooleanField(default=False)),
                ('election', models.ForeignKey(db_column='election_id', on_delete=django.db.models.deletion.CASCADE, to='hello.election')),
                ('user', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='hello.useraccount')),
            ],
            options={
                'db_table': 'election_voter_status',
                'unique_together': {('election', 'user')},
            },
        ),
    ]
