# Generated by Django 5.0.4 on 2024-07-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentname', models.CharField(max_length=255)),
                ('departmentid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
    ]
