# Generated by Django 5.0.4 on 2024-07-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='scheduled', max_length=10),
        ),
    ]
